steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/festive-kayak-412800/web-templebeer/templebeer-2:latest', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/festive-kayak-412800/web-templebeer/templebeer-2:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'templebeer-2', '--image', 'us-central1-docker.pkg.dev/festive-kayak-412800/web-templebeer/templebeer-2:latest', '--region', 'us-central1']
images:
  - 'us-central1-docker.pkg.dev/festive-kayak-412800/web-templebeer/templebeer-2:latest'